#:schema https://json.schemastore.org/cargo.json

[package]
name = "ybd-core"
version.workspace = true
edition.workspace = true
description = "Bilibili 资源下载与解析核心库"
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
reqwest.workspace = true
tokio.workspace = true
thiserror.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
qrcode.workspace = true
regex.workspace = true
urlencoding.workspace = true
md5.workspace = true
sanitize-filename.workspace = true
colored.workspace = true
futures.workspace = true
indicatif.workspace = true
mp4ameta.workspace = true
httpdate.workspace = true
